#!/bin/bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cache_file="$repo_root/docs/analysis/dizzyasset-docs-routing-cache.md"
tmp_file="$(mktemp)"

mkdir -p "$(dirname "$cache_file")"

cat > "$tmp_file" <<'EOF'
# DizzyAsset Docs Routing Cache

Repo-local summary for agents that need to reuse the docs layout without rescanning the full tree.
Generated by `scripts/sync-docs-routing-cache.sh`.

## Purpose
- Keep the canonical docs locations short and explicit.
- Reduce repeated discovery work for agents that need to know where plans, logs, workflows, and policy files live.
- Preserve the source docs as the truth; this file is only a cache.

## Canonical Read Order
1. `AGENTS.md`
2. `docs/history.md`
3. `docs/agent-policy/3-stage-pipeline.md`
4. `docs/agent-policy/serena-integration.md`
5. `docs/agent-policy/semble_rs-operation-guide.md`
6. `docs/agent-log/README.md`
7. `docs/agent-log/LOGGING_POLICY.md`
8. `docs/agent-log/WORK_LOG_TEMPLATE.md`
9. `docs/workflows/implementation-task.md`
10. `docs/workflows/verification-review.md`
11. `docs/templates/handoff.md`
12. `docs/templates/review-report.md`

## docs/ Tree Map
EOF

docs_root="$repo_root/docs"
if [ -d "$docs_root/agent-log" ]; then
  printf '%s\n' "- \`docs/agent-log/\`: task logs and work reports" >> "$tmp_file"
fi
if [ -d "$docs_root/agent-policy" ]; then
  printf '%s\n' "- \`docs/agent-policy/\`: execution rules and tool guides" >> "$tmp_file"
fi
if [ -d "$docs_root/analysis" ]; then
  printf '%s\n' "- \`docs/analysis/\`: repo-local summaries and routing cache" >> "$tmp_file"
fi
if [ -d "$docs_root/guidelines" ]; then
  printf '%s\n' "- \`docs/guidelines/\`: technical guidelines" >> "$tmp_file"
fi
if [ -d "$docs_root/knowledge" ]; then
  printf '%s\n' "- \`docs/knowledge/\`: reusable lessons and notes" >> "$tmp_file"
fi
if [ -d "$docs_root/product" ]; then
  printf '%s\n' "- \`docs/product/\`: PRDs and design docs" >> "$tmp_file"
fi
if [ -d "$docs_root/superpowers/plans" ]; then
  printf '%s\n' "- \`docs/superpowers/plans/\`: execution plans for non-trivial tasks" >> "$tmp_file"
fi
if [ -d "$docs_root/task" ]; then
  printf '%s\n' "- \`docs/task/\`: task specs and review reports" >> "$tmp_file"
fi
if [ -d "$docs_root/templates" ]; then
  printf '%s\n' "- \`docs/templates/\`: shared templates" >> "$tmp_file"
fi
if [ -d "$docs_root/workflows" ]; then
  printf '%s\n' "- \`docs/workflows/\`: workflow checklists and handoff flow" >> "$tmp_file"
fi

cat >> "$tmp_file" <<'EOF'
- root docs: `AGENTS.md` and `history.md`

## Update Rules
- Update source policy docs first.
- Update this cache only after the source docs are settled.
- Keep the cache short; add deltas, do not rewrite history.
- Rebuild this file with `scripts/sync-docs-routing-cache.sh` after docs-tree changes.

## Cross-Repo Note
- Do not assume another repo uses the same `docs/` layout.
- Re-derive the folder map per repository before copying this pattern.
EOF

if [ "${1:-}" = "--check" ]; then
  if ! diff -u "$cache_file" "$tmp_file"; then
    rm -f "$tmp_file"
    exit 1
  fi
  rm -f "$tmp_file"
  exit 0
fi

mv "$tmp_file" "$cache_file"
